export const categories = [
  "All",
  "Breakfast",
  "Lunch & Dinner",
  "Dessert",
  "Children's",
];

export const dishes = [
  {
    name: "Big Brekky",
    info: "Two eggs (fried, poached or scrambled), grilled tomato, bacon, sausage, sauteed mushrooms, hash brown & toast",
    image: "big-brekky.webp",
    price: 13,
    category: 1,
  },
  {
    name: "Vegi Big Brekky",
    info: "Two eggs (fried, poached or scrambled), grilled asparagus, tomato, sauteed mushrooms, hash brown & toast",
    image: "vegi-big-brekky.webp",
    price: 12,
    category: 1,
  },
  {
    name: "Works Omelette",
    info: "Made with three eggs, ham, mushrooms, capsicum, cheese, tomato, onion & toast",
    image: "works-omelette.webp",
    price: 11,
    category: 1,
  },
  {
    name: "Eggs Benedict",
    info: "Poached eggs served on toasted turkish bread with hollandaise sauce & fresh spinach with Ham or Smoked Salmon",
    image: "eggs-benedict.webp",
    price: 14,
    category: 1,
  },
  {
    name: "Pancakes",
    info: "Three buttermilk pancakes topped with maple syrup, berry compote and ice cream",
    image: "pancakes.webp",
    price: 9,
    category: 1,
  },
  {
    name: "Garlic Prawns",
    info: "Prawn cutlets sauteed in a white wine garlic cream served on jasmine rice",
    image: "garlic-prawns.webp",
    price: 28,
    category: 2,
  },
  {
    name: "Grilled Barramundi",
    info: "Grilled Barramundi served with rocket, pumpkin & pine nut salad with mango salsa & chips",
    image: "grilled-barramundi.webp",
    price: 22,
    category: 2,
  },
  {
    name: "Salt and Pepper Calamari",
    info: "Tender strips of lightly seasoned calamari, shallow fried with chips",
    image: "salt-pepper-calamari.webp",
    price: 18,
    category: 2,
  },
  {
    name: "Seafood Basket",
    info: "Selection of crumbed & battered fish, scallops, calamari & prawn cutlets served with chips, salad & tartare sauce",
    image: "seafood-basket.webp",
    price: 38,
    category: 2,
  },
  {
    name: "Chicken Parma",
    info: "Grilled crumbed chicken breast fillet topped with a ham, a rich Napoli sauce and mozzarella cheese served with chips and fresh garden salad",
    image: "chicken-parma.webp",
    price: 17,
    category: 2,
  },
  {
    name: "Chicken Fettuccine Carbonara",
    info: "Fresh fettuccine with chicken, bacon & garlic finished with a white wine & cream sauce",
    image: "chicken-fettuccine-carbonara.webp",
    price: 19,
    category: 2,
  },
  {
    name: "Vegetarian Fettuccine",
    info: "Sauteed mushrooms, roasted capsicum, Spanish onion, baby spinach semi sundried tomato tossed with roast tomato napoli",
    image: "vegetarian-fettuccine.webp",
    price: 17,
    category: 2,
  },
  {
    name: "Caesar Salad",
    info: "Coz lettuce, bacon, parmesan, croutons, Caesar dressing with your choice of grilled chicken, smoked salmon or calamari",
    image: "caesar-salad.webp",
    price: 10,
    category: 2,
  },
  {
    name: "Pumpkin & Parmesan Salad",
    info: "Mesclun lettuce, pumpkin, red onion, parmesan, toasted pine nuts with honey mustard dressing with your choice of grilled chicken or peppered beef",
    image: "pumpkin-parmesan-salad.webp",
    price: 10,
    category: 2,
  },
  {
    name: "Veggie Burger",
    info: "Vegetarian patty, lettuce, tomato, beetrott & vegie relish served with chips",
    image: "veggie-burger.webp",
    price: 11,
    category: 2,
  },
  {
    name: "Bourbon St Mud",
    info: "Rich chocolate mousse cake topped with chocolate ganache",
    image: "bourbon-st-mud.webp",
    price: 8,
    category: 3,
  },
  {
    name: "Choc Caramel Cheesecake",
    info: "Baked New York cheesecake topped with caramel ganache and chocolate",
    image: "choc-caramel-cheesecake.webp",
    price: 10,
    category: 3,
  },
  {
    name: "Coconut Lime Cheesecake",
    info: "Baked cheesecake infused with lime juice on a coconut biscuit crumb base and topped with toasted shredded coconut",
    image: "coconut-lime-cheesecake.webp",
    price: 10,
    category: 3,
  },
  {
    name: "Sticky Date",
    info: "Sticky date cake topped with caramel ganache served with ice cream",
    image: "sticky-date.webp",
    price: 8,
    category: 3,
  },
  {
    name: "Apple Crumble",
    info: "Apple, raspberries and sultanas topped with a cinnamon crumble and dusted with snow",
    image: "apple-crumble.webp",
    price: 9,
    category: 3,
  },
  {
    name: "Hawaiian Pizza",
    info: "Classic Hawaiian Pizza combines pizza sauce, cheese, cooked ham, and pineapple with a sprinkle of crispy bacon",
    image: "hawaiian-pizza.webp",
    price: 18,
    category: 4,
  },
  {
    name: "Chicken Tenders & Chips",
    info: "Chicken tenders are coated in ground potato chips and baked for the ultimate crispy chicken tender",
    image: "chicken-tenders-chips.webp",
    price: 14,
    category: 4,
  },
  {
    name: "Calamari & Chips",
    info: "Try this baked, battered calamari with our secret ingredient of kiwifruit to bring out its natural sweetness",
    image: "calamari-chips.webp",
    price: 16,
    category: 4,
  },
  {
    name: "Fettuccine Bolognaise",
    info: "Creamy fettuccine bolognese combines tasty fettuccine with the savory flavors that are typical for lasagna and bolognese",
    image: "fettuccine-bolognaise.webp",
    price: 13,
    category: 4,
  },
];
